# -*- coding: utf-8 -*-
"""ASSIGNMENT 1:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFHXT-HgNkXwzrKaXWu0Cyh-V8aKir5o

Task 1: Perform Basic Mathematical Operations
"""

# Task 1: Perform Basic Mathematical Operations

# Step 1: Take input from user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Step 2: Perform operations
addition = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2

# Handle division by zero
if num2 != 0:
    division = num1 / num2
else:
    division = "Undefined (cannot divide by zero)"

# Step 3: Display results
print("\nResults:")
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

"""Task 2: Create a Personalized Greeting

"""

# Task 2: Create a Personalized Greeting

# Step 1: Take input from user
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

# Step 2: Concatenate full name
full_name = first_name + " " + last_name

# Step 3: Print greeting message
print("\nHello, " + full_name + "! Welcome to the Python world.")