# -*- coding: utf-8 -*-
"""Assignment2. part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mQAZ4B4PugbzWc-iXXxX1c0hZVcwl9q

Task 1: Check if a Number is Even or Odd
"""

# Task 1: Check if a Number is Even or Odd

# 1. Take input from the user
number = int(input("Enter an integer: "))

# 2. Check if the number is even or odd
if number % 2 == 0:
    print(f"{number} is Even.")
else:
    print(f"{number} is Odd.")