# -*- coding: utf-8 -*-
"""ASSIGNMENT 1:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFHXT-HgNkXwzrKaXWu0Cyh-V8aKir5o

Task 1: Perform Basic Mathematical Operations
"""

# Task 1: Perform Basic Mathematical Operations

# Step 1: Take input from user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Step 2: Perform operations
addition = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2

# Handle division by zero
if num2 != 0:
    division = num1 / num2
else:
    division = "Undefined (cannot divide by zero)"

# Step 3: Display results
print("\nResults:")
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

"""Task 2: Sum of Integers from 1 to 50 Using a Loop


"""

# Task 2: Sum of Integers from 1 to 50 Using a Loop

# Initialize the sum variable
total_sum = 0

# Use a for loop to iterate from 1 to 50
for i in range(1, 51):
    total_sum += i

# Display the final sum
print("The sum of integers from 1 to 50 is:", total_sum)