# -*- coding: utf-8 -*-
"""Assignment1 part 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mQAZ4B4PugbzWc-iXXxX1c0hZVcwl9q

Task 2: Create a Personalized Greeting
"""

# Task 2: Create a Personalized Greeting

# Step 1: Take input from user
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
.
# Step 2: Concatenate full name
full_name = first_name + " " + last_name

# Step 3: Print greeting message
print("\nHello, " + full_name + "! Welcome to the Python world.")